### ISSUE TITLE
RealtimeConf Call For Speakers

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/talks#1]
http://realtimeconf.com/call-for-speakers/

> RealtimeConf focuses on the future of Open Web with a particular interest in realtime communication. Talks can be on any and all things related to realtime technologies and all aspects of related work (not strictly technical). Please feel free to submit multiple talks.

The conference is October 6th - 9th. I can't find whether it's in either Tri-Cities, Washington, or in Portland, OR. but it's somewhere in that area if I remember correctly.

We should propose a talk on the challenges of designing for IRC / Slack / Open Source / Closed Source / Centralization etc. 

cc @bnvk @jancborchardt @erming @jdittrich

**Comment by jancborchardt** [comment]
Yup, good call! Will anyone of us be near there at that time? I most probably won't be.

**Comment by jdittrich** [comment]
Sadly I won’t be around in the US.

**Comment by simonv3** [comment]
I don't have any plans for the period of time, and my partner's family lives in the area, so that's always a good excuse, so I'm happy to give it a stab if no one else is there. @bnvk were you thinking of heading there around that time?

**Comment by bnvk** [comment]
I had no plans to be in Portland in October, but I might be going back for some personal business in the next 2 - 5 months, so who knows... if they pay for travel though, might make sense for whomever to attend :)

**Comment by elioqoshi** [comment]
Will anyone be attending this? I might apply with a more polished talk of mine like at OpenTechSummit. Seems they sponsor travel and accomodation too.

**Comment by simonv3** [comment]
@elioqoshi the conversation hasn't really progressed beyond this. You should definitely submit your talk! Post it here if you want feedback :)

**Comment by jancborchardt** [comment]
@elioqoshi yep, go for it! :)

**Comment by simonv3** [comment]
This deadline is tomorrow by the way if anyone is interested in submitting something :)

**Comment by elioqoshi** [comment]
Found out Im not available on these dates, another time I hope :/

**Comment by bnvk** [comment]
Since this is long passed, closing it!
