### ISSUE TITLE
Submit a proposal to FSCONS

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/talks#2]
FSCONS has opened their [2015 CfP](https://frab.fscons.org/en/fscons2015/cfp/session/new)

Two topics they are looking for are:
- Everyday Crypto
- Groundbreaking User Experience

I think we should definitely submit a talk, what do you say @jancborchardt ?

**Comment by jancborchardt** [comment]
Yup, I wanted to go to FSCONS for a while already but have never managed so far.

**Comment by bnvk** [comment]
Long past, closing!
