### ISSUE TITLE
Webpage 404's

### ISSUE THREAD

**Issue by jdorfman** [opensourcedesign/talks#4]
When clicking `http://opensourcedesign.net/talks/` from this projects description:

![image](https://cloud.githubusercontent.com/assets/398230/19216024/0cf6dd28-8d63-11e6-9ef0-13817088b2f8.png)

**Comment by evalica** [comment]
There is no index.html defined for this repository, so in a way it's normal that you get 404. 
The easy fix would be to 'fix' the description. The hard fix would be to provide such a page on opensourcedesign.net

**Comment by simonv3** [comment]
Is it possible to make jekyll read the readme as the index page? We probably need to set up the config like we've done for [events](https://github.com/opensourcedesign/events/blob/gh-pages/_config.yml) (note the baseurl variable).

**Comment by bnvk** [comment]
Huh, in addition to a **proposals** folder, I just created an `index.html` and as per [the documentation](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) changed the setting for this repo but the page is still 404'ing. Will further investigate in coming days as I clean repos up!

**Comment by Erioldoesdesign** [comment]
I think the idea is to delete/merge this repo with the main open source design website repo which would hopefully, stop 404 pages. 

Anyone on this thread up for doing that?

**Comment by RDIL** [comment]
I was planning to do that, so closing this.
